// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Toems_ServiceCore.Data;

#nullable disable

namespace Toems_ServiceCore.Migrations
{
    [DbContext(typeof(ToemsDbContext))]
    [Migration("20260312145528_IdentityInit")]
    partial class IdentityInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Toems_Common.Entity.EntityComputer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("computer_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdDisabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ad_disabled");

                    b.Property<string>("AdGuid")
                        .HasColumnType("longtext")
                        .HasColumnName("ad_guid");

                    b.Property<DateTime?>("ArchiveDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("datetime_archived_local");

                    b.Property<int>("CertificateId")
                        .HasColumnType("int")
                        .HasColumnName("certificate_id");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("longtext")
                        .HasColumnName("client_version");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("computer_description");

                    b.Property<string>("Guid")
                        .HasColumnType("longtext")
                        .HasColumnName("computer_guid");

                    b.Property<int>("ImageId")
                        .HasColumnType("int")
                        .HasColumnName("image_id");

                    b.Property<int>("ImageProfileId")
                        .HasColumnType("int")
                        .HasColumnName("image_profile_id");

                    b.Property<string>("ImagingClientId")
                        .HasColumnType("longtext")
                        .HasColumnName("imaging_client_id");

                    b.Property<string>("ImagingMac")
                        .HasColumnType("longtext")
                        .HasColumnName("imaging_mac");

                    b.Property<string>("InstallationId")
                        .HasColumnType("longtext")
                        .HasColumnName("installation_id");

                    b.Property<bool>("IsAdSync")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_ad_sync");

                    b.Property<DateTime>("LastCheckinTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_checkin_time_local");

                    b.Property<DateTime>("LastInventoryTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_inventory_time_local");

                    b.Property<string>("LastIp")
                        .HasColumnType("longtext")
                        .HasColumnName("last_ip");

                    b.Property<string>("LastSocketResult")
                        .HasColumnType("longtext")
                        .HasColumnName("last_socket_result");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("computer_name");

                    b.Property<int>("ProvisionStatus")
                        .HasColumnType("int")
                        .HasColumnName("provision_status");

                    b.Property<DateTime>("ProvisionedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("provisioned_time_local");

                    b.Property<string>("PushUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("push_url");

                    b.Property<string>("PxeDns")
                        .HasColumnType("longtext")
                        .HasColumnName("pxe_dns");

                    b.Property<string>("PxeGateway")
                        .HasColumnType("longtext")
                        .HasColumnName("pxe_gateway");

                    b.Property<string>("PxeIpAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("pxe_ip_address");

                    b.Property<string>("PxeNetmask")
                        .HasColumnType("longtext")
                        .HasColumnName("pxe_netmask");

                    b.Property<string>("RemoteAccessId")
                        .HasColumnType("longtext")
                        .HasColumnName("remote_access_id");

                    b.Property<string>("SymmKeyEncrypted")
                        .HasColumnType("longtext")
                        .HasColumnName("symmetric_key_enc");

                    b.Property<string>("UUID")
                        .HasColumnType("longtext")
                        .HasColumnName("hardware_uuid");

                    b.Property<int>("WinPeModuleId")
                        .HasColumnType("int")
                        .HasColumnName("winpe_module_id");

                    b.HasKey("Id");

                    b.ToTable("computers");
                });

            modelBuilder.Entity("Toems_ServiceCore.Data.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Toems_ServiceCore.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Toems_ServiceCore.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toems_ServiceCore.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Toems_ServiceCore.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
