<%@ Page Title="" Language="C#" MasterPageFile="~/views/admin/admin.master" AutoEventWireup="true" CodeBehind="server.aspx.cs" Inherits="Toems_FrontEnd.views.admin.server" %>
<asp:Content runat="server" ContentPlaceHolderID="TopBreadCrumbSub1">
    <li>Server</li>
</asp:Content>
<asp:Content runat="server" ContentPlaceHolderID="SubNavTitle_Sub1">
    Admin Settings
</asp:Content>
<asp:Content ID="Content1" ContentPlaceHolderID="DropDownActionsSub" Runat="Server">
    <li><asp:LinkButton ID="btnUpdateSettings" runat="server" Text="Update Server Settings" OnClick="btnUpdateSettings_OnClick" CssClass="main-action"/></li>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="SubContent" Runat="Server">
    <script type="text/javascript">
        $(document).ready(function() {
            $('#server').addClass("nav-current");
        });
    </script>
    <div class="size-4 column">
        Organization Name:
    </div>
    <div class="size-5 column">
        <asp:TextBox ID="txtOrganization" runat="server" CssClass="textbox"></asp:TextBox>
    </div>
    <br class="clear"/>

    <div class="size-4 column">
            Default Computers Page:
        </div>
        <div class="size-5 column">
            <asp:DropDownList ID="ddlComputerView" runat="server" CssClass="ddlist">
                <asp:ListItem>Active</asp:ListItem>
                <asp:ListItem>Image Only</asp:ListItem>
                <asp:ListItem>All</asp:ListItem>
            </asp:DropDownList>
        </div>
        <br class="clear"/>
  
  

</asp:Content>
<asp:Content runat="server" ContentPlaceHolderID="subHelp">
    <h5><span style="color: #ff9900;">Organization Name:</span></h5>
<p>The name of your organization, this will be displayed in all certificates generated by Theopenem.</p>
<p>&nbsp;</p>

</asp:Content>
